language: php

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.7.*
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.*

matrix:
  exclude:
    - php: 7.2
      env: LARAVEL_VERSION=5.5.*
    - php: 7.3
      env: LARAVEL_VERSION=5.5.*
    - php: 7.4
      env: LARAVEL_VERSION=5.5.*
    - php: 7.3
      env: LARAVEL_VERSION=5.6.*
    - php: 7.4
      env: LARAVEL_VERSION=5.6.*
    - php: 7.3
      env: LARAVEL_VERSION=5.7.*
    - php: 7.4
      env: LARAVEL_VERSION=5.7.*
    - php: 5.6
      env: LARAVEL_VERSION=5.8.*
    - php: 7.0
      env: LARAVEL_VERSION=5.8.*
    - php: 7.1
      env: LARAVEL_VERSION=5.8.*
    - php: 7.3
      env: LARAVEL_VERSION=5.8.*
    - php: 7.4
      env: LARAVEL_VERSION=5.8.*
    - php: 5.6
      env: LARAVEL_VERSION=5.7
    - php: 5.6
      env: LARAVEL_VERSION=5.8
    - php: 5.6
      env: LARAVEL_VERSION=6.*
    - php: 7.0
      env: LARAVEL_VERSION=6.*
    - php: 7.1
      env: LARAVEL_VERSION=6.*

jobs:
  fast_finish: true

sudo: false

before_install:
  # ensure that the specific Laravel version is required
  - composer require "illuminate/support:${LARAVEL_VERSION}" --no-update
  - cat composer.json
  - echo ${LARAVEL_VERSION}

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - mysql -e 'create database closuretabletest;'

script: vendor/bin/phpunit

branches:
  only:
    - master
    - feature/laravel-5
    - 6.x
    - travis-ci-for-6.x
    # version tag, e.g. v1.0.0
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^\d+\.\d+?$/
